"""Make Lab product limits shared by API validation and UI."""

MAKE_LAB_IMAGES_MIN = 1
MAKE_LAB_IMAGES_MAX = 5

MAKE_LAB_GENERATION_COUNT_MIN = 1
MAKE_LAB_GENERATION_COUNT_MAX = 999

MAKE_LAB_UPSCALE_MODEL_DEFAULT = "RealESRGAN_x2.pth"
MAKE_LAB_UPSCALE_BY_DEFAULT = 1.5
MAKE_LAB_REFINE_STEPS_DEFAULT = 15
MAKE_LAB_REFINE_DENOISE_DEFAULT = 0.35
